FROM node:24.16.0@sha256:40ad9f3064e67d6860b4bc3fe1880b2953934fd6320ada990e45fe0efa6badd7
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1 -y

RUN mkdir /src/

WORKDIR /src/

USER node
