FROM node:24.18.1@sha256:19cd848a0e073d34bd8cd5545a1b6b4d28489b3e3b607366621ced442bd5f6b4
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1 -y

RUN mkdir /src/

WORKDIR /src/

USER node
