# This file was generated by django-aqueduct (codegen v2).
# Regenerate with `manage.py generate_aqueduct_settings`.
#
# Code inside `# >>> aqueduct:generated:*` regions is overwritten on every run.
# Add validators and overrides inside `# >>> aqueduct:preserved:*` regions
# (or anywhere outside a generated region) — they survive regeneration.


# >>> aqueduct:generated:imports
from __future__ import annotations

import ast
import json
import logging
import platform
from typing import Annotated, Any

from odl_video.envs import get_int, get_string
from pydantic import AliasChoices, Field, field_validator
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict
from redbeat import RedBeatScheduler

# <<< aqueduct:generated:imports

# ---------------------------------------------------------------------------
# Hand-written support code. Everything outside the `aqueduct:generated:*`
# regions (including the `aqueduct:preserved:validators` region inside the
# class) survives regeneration — `manage.py generate_aqueduct_settings`
# merges fresh output into the generated regions only.
#
# Deliberately NOT modelled as fields:
#   * LOGGING — built by mitol.observability.settings.logging via a factory
#     that reads django.conf.settings.DEBUG at logging-configuration time
#     (after settings are fully loaded); the settings_aqueduct*.py shims
#     import it the same way odl_video/settings.py does.
#   * LOG_LEVEL / DJANGO_LOG_LEVEL — defined by that same mitol module.
# ---------------------------------------------------------------------------

import os
import pathlib
from urllib.parse import urljoin

from django.core.exceptions import ImproperlyConfigured
from django_aqueduct import derivations as dv
from django_aqueduct.sources.dev import vault_source_from_env
from pydantic import model_validator
from pydantic_settings import PydanticBaseSettingsSource

from odl_video.envs import get_any

# odl_video/settings.py computes BASE_DIR as the parent of the odl_video
# package directory. This module lives in the same package, so the same
# computation applies unchanged, keeping the value portable across
# machines/containers instead of frozen at generation time.
_DEFAULT_BASE_DIR = str(pathlib.Path(__file__).resolve().parent.parent)


class _FeatureFlagEnvSource(PydanticBaseSettingsSource):
    """Surface dynamic ``FEATURE_*`` environment variables to the model.

    pydantic-settings' env source only supplies values for declared fields, so
    an open-ended ``FEATURE_*`` scan cannot arrive through it. This source
    injects those keys (coerced with the same ``get_any`` bool/int/str parsing
    odl_video/settings.py uses) as model extras, so the ``FEATURES`` derivation
    can read them from the model via ``derivations.feature_flags`` — alongside
    flags supplied by any other source (e.g. Vault) — instead of scanning
    ``os.environ`` directly.
    """

    def get_field_value(self, field, field_name):  # noqa: ARG002 - per-field hook unused
        return None, field_name, False

    def __call__(self):
        prefix = os.environ.get("ODL_VIDEO_FEATURES_PREFIX", "FEATURE_")
        return {key: get_any(key, None) for key in os.environ if key.startswith(prefix)}


class AqueductSettings(BaseSettings):
    """Typed Django settings model generated by django-aqueduct."""

    model_config = SettingsConfigDict(env_prefix="", extra="allow")

    # >>> aqueduct:generated:fields
    # ===== mitol.common.envs =====
    POST_TRANSCODE_ACTIONS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [],
        validation_alias=AliasChoices("POST_TRANSCODE_ACTIONS"),
        description="Actions to perform before publish",
    )
    TRANSCODE_JOB_TEMPLATE: str = Field(
        default="",
        validation_alias=AliasChoices("TRANSCODE_JOB_TEMPLATE"),
        description="Path to the transcoding job template",
    )
    VIDEO_S3_THUMBNAIL_PREFIX: str = Field(
        default="",
        validation_alias=AliasChoices("VIDEO_S3_THUMBNAIL_PREFIX"),
        description="Prefix for the thumbnail video",
    )
    VIDEO_S3_TRANSCODE_ENDPOINT: str = Field(
        default="aws_mediaconvert_transcodes",
        validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_ENDPOINT"),
        description="Endpoint to be used for AWS MediaConvert",
    )
    VIDEO_S3_UPLOAD_PREFIX: str = Field(
        default="",
        validation_alias=AliasChoices("VIDEO_S3_UPLOAD_PREFIX"),
        description="Prefix for the source video",
    )
    VIDEO_TRANSCODE_QUEUE: str = Field(
        default="Default",
        validation_alias=AliasChoices("VIDEO_TRANSCODE_QUEUE"),
        description="Name of MediaConvert queue to use for transcoding",
    )
    # ===== odl_video.settings =====
    ADMINS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    ADMIN_EMAIL: str = Field(
        default="",
        validation_alias=AliasChoices("ODL_VIDEO_ADMIN_EMAIL"),
        description="e-mail configurable admins",
    )
    ADWORDS_CONVERSION_ID: str = Field(
        default="", validation_alias=AliasChoices("ADWORDS_CONVERSION_ID")
    )
    ALLOWED_HOSTS: Annotated[list[Any], NoDecode] = Field(default_factory=lambda: ["*"])
    AUTHENTICATION_BACKENDS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AWS_ACCESS_KEY_ID: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_ACCESS_KEY_ID")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_ACCOUNT_ID: str = Field(
        default="", validation_alias=AliasChoices("AWS_ACCOUNT_ID")
    )
    AWS_REGION: str = Field(default="", validation_alias=AliasChoices("AWS_REGION"))
    AWS_ROLE_NAME: str = Field(
        default="", validation_alias=AliasChoices("AWS_ROLE_NAME")
    )
    AWS_S3_CUSTOM_DOMAIN: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AWS_S3_DOMAIN: str = Field(
        default="s3.amazonaws.com", validation_alias=AliasChoices("AWS_S3_DOMAIN")
    )
    AWS_S3_UPLOAD_IO_CHUNKSIZE_KB: int = Field(
        default=256, validation_alias=AliasChoices("AWS_S3_UPLOAD_IO_CHUNKSIZE_KB")
    )
    AWS_S3_UPLOAD_MAX_CONCURRENCY: int = Field(
        default=10, validation_alias=AliasChoices("AWS_S3_UPLOAD_MAX_CONCURRENCY")
    )
    AWS_S3_UPLOAD_MAX_IO_QUEUE: int = Field(
        default=100, validation_alias=AliasChoices("AWS_S3_UPLOAD_MAX_IO_QUEUE")
    )
    AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB: int = Field(
        default=32,
        validation_alias=AliasChoices("AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB"),
    )
    AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB: int = Field(
        default=32,
        validation_alias=AliasChoices("AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB"),
    )
    AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS: int = Field(
        default=5, validation_alias=AliasChoices("AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS")
    )
    AWS_S3_UPLOAD_TRANSFER_CONFIG: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    AWS_S3_UPLOAD_USE_THREADS: bool = Field(
        default=True, validation_alias=AliasChoices("AWS_S3_UPLOAD_USE_THREADS")
    )
    AWS_SECRET_ACCESS_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("AWS_SECRET_ACCESS_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    AWS_STORAGE_BUCKET_NAME: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_BUCKET")
    )
    AWS_TRANSCODE_BUCKET_NAME: str = Field(
        default="", validation_alias=AliasChoices("AWS_TRANSCODE_BUCKET_NAME")
    )
    BASE_DIR: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CACHES: Any = Field(
        default=None, description="django cache back-ends"
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_ACCEPT_CONTENT: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["json"]
    )
    CELERY_BEAT_SCHEDULE: Any = Field(
        default_factory=lambda: {
    "update-youtube-statuses": {
        "task": "cloudsync.tasks.update_youtube_statuses",
        "schedule": get_int("VIDEO_STATUS_UPDATE_FREQUENCY", 60),
    },
    "watch-bucket": {
        "task": "cloudsync.tasks.monitor_watch_bucket",
        "schedule": get_int("VIDEO_WATCH_BUCKET_FREQUENCY", 900),
    },
    "upload_youtube_videos": {
        "task": "cloudsync.tasks.upload_youtube_videos",
        "schedule": get_int("YT_UPLOAD_FREQUENCY", 3600),
    },
    "fail-stuck-uploading-videos": {
        "task": "cloudsync.tasks.fail_stuck_uploading_videos",
        "schedule": get_int("STUCK_UPLOADING_CHECK_FREQUENCY", 3600),
    },
},
    )  # TODO: refine type
    CELERY_BEAT_SCHEDULER: Any = Field(
        default_factory=lambda: RedBeatScheduler
    )  # TODO: refine type
    CELERY_BROKER_TRANSPORT_OPTIONS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_BROKER_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("CELERY_BROKER_URL")
    )  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_BROKER_VISIBILITY_TIMEOUT: int = Field(
        default_factory=lambda: 60 * 60,
        validation_alias=AliasChoices("CELERY_BROKER_VISIBILITY_TIMEOUT"),
        description="Redis-broker redelivery window for unacked messages (also applied to\nCELERY_BROKER_TRANSPORT_OPTIONS below). The per-video lock — not this value —\nprevents concurrent double-uploads, so it can be short for faster crash\nrecovery; floor is the longest task ETA (retry backoffs, ~10m).",  # noqa: E501
    )
    CELERY_REDBEAT_REDIS_URL: str | None = Field(
        default=None
    )  # REDACTED: name looks secret-like — set via a source, not here
    CELERY_REDIS_MAX_CONNECTIONS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_RESULT_BACKEND: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    CELERY_RESULT_SERIALIZER: str = Field(default="json")
    CELERY_TASK_ALWAYS_EAGER: bool = Field(
        default=False, validation_alias=AliasChoices("CELERY_TASK_ALWAYS_EAGER")
    )
    CELERY_TASK_EAGER_PROPAGATES: bool = Field(
        default=True, validation_alias=AliasChoices("CELERY_TASK_EAGER_PROPAGATES")
    )
    CELERY_TASK_SEND_SENT_EVENT: bool = Field(default=True)
    CELERY_TASK_SERIALIZER: str = Field(default="json")
    CELERY_TASK_TRACK_STARTED: bool = Field(default=True)
    CELERY_TIMEZONE: str = Field(default="UTC")
    CLOUDFRONT_DIST: str | None = Field(
        default=None, validation_alias=AliasChoices("STATIC_CLOUDFRONT_DIST")
    )
    CLOUDFRONT_KEY_ID: str = Field(
        default="", validation_alias=AliasChoices("CLOUDFRONT_KEY_ID")
    )
    CLOUDFRONT_PRIVATE_KEY: str | None = Field(
        default=None, description="AWS"
    )  # REDACTED: name looks secret-like — set via a source, not here
    CLOUDSYNC_STREAM_S3_LOCK_TTL: int = Field(
        default=120,
        validation_alias=AliasChoices("CLOUDSYNC_STREAM_S3_LOCK_TTL"),
        description="Per-video upload lock lease. Must exceed the refresh interval so the heartbeat\ncan reacquire before expiry, and must stay below CELERY_BROKER_VISIBILITY_TIMEOUT\nso a dead worker's lock expires before redelivery (letting the retry re-acquire).",  # noqa: E501
    )
    CLOUDSYNC_STREAM_S3_MAX_RETRIES: int = Field(
        default=2,
        validation_alias=AliasChoices("CLOUDSYNC_STREAM_S3_MAX_RETRIES"),
        description="stream_to_s3 retry tuning",
    )
    CLOUDSYNC_STREAM_S3_RETRY_BACKOFF: int = Field(
        default=60, validation_alias=AliasChoices("CLOUDSYNC_STREAM_S3_RETRY_BACKOFF")
    )
    CLOUDSYNC_STREAM_S3_RETRY_MAX_BACKOFF: int = Field(
        default=600,
        validation_alias=AliasChoices("CLOUDSYNC_STREAM_S3_RETRY_MAX_BACKOFF"),
    )
    CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS: int = Field(
        default=60,
        validation_alias=AliasChoices("CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS"),
        description="How often the stream_to_s3 progress callback refreshes updated_at (janitor\nheartbeat) and reacquires its lock lease. Must stay below the janitor threshold\nso a healthy long-running upload isn't reaped as stuck.",  # noqa: E501
    )
    DATABASES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEBUG: bool = Field(
        default=False,
        validation_alias=AliasChoices("DEBUG"),
        description="SECURITY WARNING: don't run with debug turned on in production!",
    )
    DEFAULT_AUTO_FIELD: str = Field(default="django.db.models.AutoField")
    DEFAULT_DATABASE_CONFIG: Any = Field(
        default=None,
        description="Database\nhttps://docs.djangoproject.com/en/1.8/ref/settings/#databases\nUses DATABASE_URL to configure with sqlite default:\nFor URL structure:\nhttps://github.com/kennethreitz/dj-database-url",  # noqa: E501
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    DEFAULT_FROM_EMAIL: str = Field(
        default="webmaster@localhost",
        validation_alias=AliasChoices("ODL_VIDEO_FROM_EMAIL"),
    )
    DISABLE_WEBPACK_LOADER_STATS: bool = Field(
        default=False, validation_alias=AliasChoices("DISABLE_WEBPACK_LOADER_STATS")
    )
    DROPBOX_KEY: str = Field(
        default="",
        validation_alias=AliasChoices("DROPBOX_KEY"),
        description="Dropbox app credentials. DROPBOX_KEY (the app key) is also used by the browser\nChooser; DROPBOX_SECRET and DROPBOX_REFRESH_TOKEN authenticate server-side\nshared-link downloads (sharing/get_shared_link_file) and must stay server-only —\nnever expose them to the frontend.",  # noqa: E501
    )
    DROPBOX_REFRESH_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("DROPBOX_REFRESH_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    DROPBOX_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("DROPBOX_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_BACKEND: str = Field(
        default="django.core.mail.backends.smtp.EmailBackend",
        validation_alias=AliasChoices("ODL_VIDEO_EMAIL_BACKEND"),
        description="Configure e-mail settings",
    )
    EMAIL_HOST: str = Field(
        default="localhost", validation_alias=AliasChoices("ODL_VIDEO_EMAIL_HOST")
    )
    EMAIL_HOST_PASSWORD: str | None = Field(
        default=None, validation_alias=AliasChoices("ODL_VIDEO_EMAIL_PASSWORD")
    )  # REDACTED: name looks secret-like — set via a source, not here
    EMAIL_HOST_USER: str = Field(
        default="", validation_alias=AliasChoices("ODL_VIDEO_EMAIL_USER")
    )
    EMAIL_PORT: int = Field(
        default=25, validation_alias=AliasChoices("ODL_VIDEO_EMAIL_PORT")
    )
    EMAIL_SUPPORT: str = Field(
        default="support@example.com",
        validation_alias=AliasChoices("ODL_VIDEO_SUPPORT_EMAIL"),
    )
    EMAIL_USE_TLS: bool = Field(
        default=False, validation_alias=AliasChoices("ODL_VIDEO_EMAIL_TLS")
    )
    ENABLE_VIDEO_PERMISSIONS: bool = Field(
        default=False, validation_alias=AliasChoices("ENABLE_VIDEO_PERMISSIONS")
    )
    ENFORCE_MANDATORY_SETTINGS: bool = Field(
        default=True,
        validation_alias=AliasChoices("ENFORCE_MANDATORY_SETTINGS"),
        description="We want to be able to optionally disable mandatory settings. e.g. when running\ncollectstatic",  # noqa: E501
    )
    ENVIRONMENT: str = Field(
        default="dev", validation_alias=AliasChoices("ODL_VIDEO_ENVIRONMENT")
    )
    FEATURES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    FIELD_ENCRYPTION_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("FIELD_ENCRYPTION_KEY")
    )  # REDACTED: name looks secret-like — set via a source, not here
    GA_DIMENSION_CAMERA: str = Field(
        default="", validation_alias=AliasChoices("GA_DIMENSION_CAMERA")
    )
    GA_KEYFILE_JSON: str = Field(
        default="", validation_alias=AliasChoices("GA_KEYFILE_JSON")
    )
    GA_TRACKING_ID: str = Field(
        default="", validation_alias=AliasChoices("GA_TRACKING_ID")
    )
    GA_VIEW_ID: str = Field(default="", validation_alias=AliasChoices("GA_VIEW_ID"))
    HIJACK_ALLOW_GET_REQUESTS: bool = Field(default=True)
    HIJACK_INSERT_BEFORE: str = Field(default="</body>", description="Hijack")
    HIJACK_LOGOUT_REDIRECT_URL: str = Field(default="/admin/auth/user")
    HOSTNAME: Any = Field(
        default_factory=lambda: platform.node().split(".")[0]
    )  # TODO: refine type
    INSTALLED_APPS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "mitol.observability.apps.ObservabilityConfig",
            "ui.apps.UIConfig",
            "cloudsync.apps.CloudSyncConfig",
            "techtv2ovs",
            "mail.apps.MailConfig",
            "django.contrib.admin",
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "django.contrib.sessions",
            "django.contrib.messages",
            "django.contrib.staticfiles",
            "rest_framework",
            "django_filters",
            "hijack",
            "hijack.contrib.admin",
            "encrypted_model_fields",
            "health_check",
        ],
    )
    INTERNAL_IPS: Any = Field(
        default_factory=lambda: (get_string("HOST_IP", "127.0.0.1"),),
        description="Important to define this so DEBUG works properly",
    )  # TODO: refine type
    KB: int = Field(
        default=1024,
        description="AWS S3 upload settings\nthe defaults values come from the default configuration in boto3.s3.transfer.TransferConfig\napart from the first 2",  # noqa: E501
    )
    KEYCLOAK_REALM: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    KEYCLOAK_SERVER_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    KEYCLOAK_SVC_ADMIN: str = Field(
        default="odl-video-app", validation_alias=AliasChoices("KEYCLOAK_SVC_ADMIN")
    )
    KEYCLOAK_SVC_ADMIN_PASSWORD: str | None = Field(
        default=None, validation_alias=AliasChoices("KEYCLOAK_SVC_ADMIN_PASSWORD")
    )  # REDACTED: name looks secret-like — set via a source, not here
    LANGUAGE_CODE: str = Field(default="en-us")
    LECTURE_CAPTURE_USER: str = Field(
        default="", validation_alias=AliasChoices("LECTURE_CAPTURE_USER")
    )
    LOGIN_REDIRECT_URL: str = Field(default="/")
    LOGIN_URL: str = Field(default="login")
    LOGOUT_REDIRECT_URL: str = Field(default="/")
    MAILGUN_BATCH_CHUNK_SIZE: int = Field(
        default=1000, validation_alias=AliasChoices("MAILGUN_BATCH_CHUNK_SIZE")
    )
    MAILGUN_BCC_TO_EMAIL: str = Field(
        default="no-reply@example.com",
        validation_alias=AliasChoices("MAILGUN_BCC_TO_EMAIL"),
    )
    MAILGUN_FROM_EMAIL: str = Field(
        default="no-reply@example.com",
        validation_alias=AliasChoices("MAILGUN_FROM_EMAIL"),
    )
    MAILGUN_KEY: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_KEY")
    )
    MAILGUN_RECIPIENT_OVERRIDE: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_RECIPIENT_OVERRIDE")
    )
    MAILGUN_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("MAILGUN_URL")
    )
    MANDATORY_SETTINGS: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "AWS_ACCESS_KEY_ID",
            "AWS_REGION",
            "AWS_ACCOUNT_ID",
            "AWS_S3_DOMAIN",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_STORAGE_BUCKET_NAME",
            "AWS_ROLE_NAME",
            "CLOUDFRONT_KEY_ID",
            "CLOUDFRONT_PRIVATE_KEY",
            "DROPBOX_KEY",
            "DROPBOX_SECRET",
            "DROPBOX_REFRESH_TOKEN",
            "GA_DIMENSION_CAMERA",
            "GA_KEYFILE_JSON",
            "GA_VIEW_ID",
            "LECTURE_CAPTURE_USER",
            "MAILGUN_KEY",
            "MAILGUN_URL",
            "ODL_VIDEO_BASE_URL",
            "REDIS_URL",
            "SECRET_KEY",
            "VIDEO_CLOUDFRONT_DIST",
            "VIDEO_CDN_DISTRIBUTION_ID",
            "VIDEO_S3_BUCKET",
            "VIDEO_S3_TRANSCODE_BUCKET",
            "VIDEO_S3_THUMBNAIL_BUCKET",
            "VIDEO_S3_SUBTITLE_BUCKET",
            "VIDEO_S3_WATCH_BUCKET",
            "VIDEO_S3_TRANSCODE_PREFIX",
            "ENABLE_VIDEO_PERMISSIONS",
            "YT_ACCESS_TOKEN",
            "YT_REFRESH_TOKEN",
            "YT_CLIENT_ID",
            "YT_CLIENT_SECRET",
        ],
        description="List of mandatory settings. If any of these is not set, the app will not start\nand will raise an ImproperlyConfigured exception",  # noqa: E501
    )
    MB: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    MIDDLEWARE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "django.middleware.security.SecurityMiddleware",
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "hijack.middleware.HijackUserMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
        ],
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS: int = Field(
        default_factory=lambda: 60 * 60,
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS"),
    )
    MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME: str = Field(
        default="ODL_VIDEO_FEATURE_FLAGS",
        validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME"),
    )
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: str | None = Field(
        default=None, validation_alias=AliasChoices("MIDDLEWARE_FEATURE_FLAG_QS_PREFIX")
    )
    NPLUSONE_LOGGER: Any = Field(
        default_factory=lambda: logging.getLogger("nplusone"),
        description="nplusone profiler logger configuration",
    )  # TODO: refine type
    NPLUSONE_LOG_LEVEL: Any = Field(
        default_factory=lambda: logging.ERROR
    )  # TODO: refine type
    ODL_VIDEO_BASE_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("ODL_VIDEO_BASE_URL"),
        description="the full URL of the current application is mandatory",
    )
    ODL_VIDEO_FEATURES_PREFIX: str = Field(
        default="FEATURE_", validation_alias=AliasChoices("ODL_VIDEO_FEATURES_PREFIX")
    )
    OPENEDX_API_CLIENT_ID: str = Field(
        default="", validation_alias=AliasChoices("OPENEDX_API_CLIENT_ID")
    )
    OPENEDX_API_CLIENT_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("OPENEDX_API_CLIENT_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    PAGE_SIZE_COLLECTIONS: int = Field(
        default=50, validation_alias=AliasChoices("PAGE_SIZE_COLLECTIONS")
    )
    PAGE_SIZE_MAXIMUM: int = Field(
        default=1000, validation_alias=AliasChoices("PAGE_SIZE_MAXIMUM")
    )
    PAGE_SIZE_QUERY_PARAM: str = Field(
        default="page_size",
        validation_alias=AliasChoices("PAGE_SIZE_QUERY_PARAM"),
        description="Paging parameters",
    )
    PAGE_SIZE_VIDEOS: int = Field(
        default=1000, validation_alias=AliasChoices("PAGE_SIZE_VIDEOS")
    )
    REACT_GA_DEBUG: bool = Field(
        default=False, validation_alias=AliasChoices("REACT_GA_DEBUG")
    )
    REDIS_MAX_CONNECTIONS: int = Field(
        default=65000, validation_alias=AliasChoices("REDIS_MAX_CONNECTIONS")
    )
    REDIS_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("REDIS_URL"),
        description="Celery\nhttp://docs.celeryproject.org/en/latest/django/first-steps-with-django.html\nA note of REDIS_URL and CELERY_BROKER_URL formats for connections utilzing TLS\nFor connections NOT utilzing TLS, setting JUST 'REDIS_URL' should be sufficient.\nFor connections that DO utilize TLS, we need to make some special accomodations\nfor how two different methods of connecting to Redis are used.\nREDIS_URL Format (aka 'uppercase constant')\nrediss://<username>:<password>@<redis-hostname>:6379/<DB#>?ssl_cert_reqs=CERT_REQUIRED  #pragma: allowlist secret\nCELERY_BROKER_URL Format (aka 'lowercase literal')\nrediss://<username>:<password>@<redis-hostname>:6379/<DB#>?ssl_cert_reqs=required  #pragma: allowlist secret\nCACHES.REDIS.LOCATION= lowercase literal\nCELERY_RESULT_BACKEND = uppercase constant\nCELERY_REDBEAT_REDIS_URL = lowercase literal",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    REST_FRAMEWORK: Annotated[dict[str, Any], NoDecode] = Field(
        default_factory=lambda: {
            "DEFAULT_AUTHENTICATION_CLASSES": (
                "rest_framework.authentication.BasicAuthentication",
                "rest_framework.authentication.SessionAuthentication",
            )
        },
    )
    ROOT_URLCONF: str = Field(default="odl_video.urls")
    SECRET_KEY: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SECRET_KEY"),
        description="SECURITY WARNING: keep the secret key used in production secret!",
    )  # REDACTED: name looks secret-like — set via a source, not here
    SECURE_CROSS_ORIGIN_OPENER_POLICY: str = Field(
        default="same-origin-allow-popups",
        validation_alias=AliasChoices("SECURE_CROSS_ORIGIN_OPENER_POLICY"),
    )
    SECURE_PROXY_SSL_HEADER: tuple[Any, ...] = Field(
        default=("HTTP_X_FORWARDED_PROTO", "https"),
        description="Trust the X-Forwarded-Proto header set by the upstream proxy (Nginx/APISix).\nThis lets Django recognise TLS-terminated requests as HTTPS so that\nrequest.is_secure() returns True and social-auth builds redirect_uris with https://.",  # noqa: E501
    )  # TODO: refine type
    SECURE_SSL_REDIRECT: bool = Field(
        default=True, validation_alias=AliasChoices("ODL_VIDEO_SECURE_SSL_REDIRECT")
    )
    SENTRY_DSN: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SENTRY_DSN"),
        description="initialize Sentry before doing anything else so we capture any config errors",  # noqa: E501
    )  # REDACTED: name looks secret-like — set via a source, not here
    SENTRY_LOG_LEVEL: str = Field(
        default="ERROR", validation_alias=AliasChoices("SENTRY_LOG_LEVEL")
    )
    SESSION_ENGINE: str = Field(
        default="django.contrib.sessions.backends.signed_cookies"
    )
    SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: str | None = Field(
        default=None,
        validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL"),
    )  # REDACTED: name looks secret-like — set via a source, not here
    SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL: str = Field(
        default="",
        validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL"),
    )
    SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["user_groups"]
    )
    SOCIAL_AUTH_KEYCLOAK_ID_KEY: str = Field(default="email")
    SOCIAL_AUTH_KEYCLOAK_KEY: str = Field(
        default="",
        validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_KEY"),
        description="Keycloak OIDC settings — consumed by social-auth-app-django at runtime.",  # noqa: E501
    )
    SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY: str = Field(
        default="", validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY")
    )
    SOCIAL_AUTH_KEYCLOAK_SCOPE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: ["openid", "profile", "email"]
    )
    SOCIAL_AUTH_KEYCLOAK_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    SOCIAL_AUTH_PIPELINE: Annotated[list[Any], NoDecode] = Field(
        default_factory=lambda: [
            "social_core.pipeline.social_auth.social_details",
            "social_core.pipeline.social_auth.social_uid",
            "social_core.pipeline.social_auth.social_user",
            "social_core.pipeline.user.get_username",
            "social_core.pipeline.user.create_user",
            "social_core.pipeline.social_auth.associate_user",
            "social_core.pipeline.social_auth.load_extra_data",
            "social_core.pipeline.user.user_details",
            "odl_video.pipeline.assign_user_groups",
        ],
        description="Social Auth Pipeline - Custom pipeline for user creation and role mapping",  # noqa: E501
    )
    SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL: bool = Field(default=True)
    STATICFILES_DIRS: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATIC_ROOT: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    STATIC_URL: str = Field(default="/static/")
    STUCK_UPLOADING_THRESHOLD_HOURS: int = Field(
        default=2,
        validation_alias=AliasChoices("STUCK_UPLOADING_THRESHOLD_HOURS"),
        description="Janitor: fail videos stuck in UPLOADING past the threshold so they can be retried.",  # noqa: E501
    )
    TEMPLATES: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    THUMBNAIL_UPLOAD_MAX_HEIGHT: int = Field(
        default=360, validation_alias=AliasChoices("THUMBNAIL_UPLOAD_MAX_HEIGHT")
    )
    THUMBNAIL_UPLOAD_MAX_SIZE: int = Field(
        default_factory=lambda: 1024 * 1024,
        validation_alias=AliasChoices("THUMBNAIL_UPLOAD_MAX_SIZE"),
    )
    THUMBNAIL_UPLOAD_MAX_WIDTH: int = Field(
        default=640, validation_alias=AliasChoices("THUMBNAIL_UPLOAD_MAX_WIDTH")
    )
    TIME_ZONE: str = Field(default="UTC")
    TRANSCODE_JOB_TEMPLATE_PORTRAIT: str = Field(
        default="config/mediaconvert_portrait.json",
        validation_alias=AliasChoices("TRANSCODE_JOB_TEMPLATE_PORTRAIT"),
    )
    UNSORTED_COLLECTION: str = Field(
        default="Unsorted", validation_alias=AliasChoices("UNSORTED_COLLECTION")
    )
    USE_CELERY: bool = Field(default=True)
    USE_I18N: bool = Field(default=True)
    USE_KEYCLOAK: bool = Field(
        default=True, validation_alias=AliasChoices("USE_KEYCLOAK")
    )
    USE_L10N: bool = Field(default=True)
    USE_TZ: bool = Field(default=True)
    USE_WEBPACK_DEV_SERVER: bool = Field(
        default=False,
        validation_alias=AliasChoices("ODL_VIDEO_USE_WEBPACK_DEV_SERVER"),
        description="Request files from the webpack dev server",
    )
    VERSION: str = Field(default="0.94.2")
    VIDEO_CDN_DISTRIBUTION_ID: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_CDN_DISTRIBUTION_ID")
    )
    VIDEO_CLOUDFRONT_BASE_URL: str | None = Field(
        default=None, validation_alias=AliasChoices("VIDEO_CLOUDFRONT_BASE_URL")
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    VIDEO_CLOUDFRONT_DIST: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_CLOUDFRONT_DIST")
    )
    VIDEO_S3_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_BUCKET")
    )
    VIDEO_S3_SUBTITLE_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_SUBTITLE_BUCKET")
    )
    VIDEO_S3_THUMBNAIL_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_THUMBNAIL_BUCKET")
    )
    VIDEO_S3_TRANSCODE_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_BUCKET")
    )
    VIDEO_S3_TRANSCODE_PREFIX: str = Field(
        default="transcoded", validation_alias=AliasChoices("VIDEO_S3_TRANSCODE_PREFIX")
    )
    VIDEO_S3_WATCH_BUCKET: str = Field(
        default="", validation_alias=AliasChoices("VIDEO_S3_WATCH_BUCKET")
    )
    WEBPACK_DEV_SERVER_HOST: str = Field(
        default="", validation_alias=AliasChoices("WEBPACK_DEV_SERVER_HOST")
    )
    WEBPACK_DEV_SERVER_PORT: int = Field(
        default=8082, validation_alias=AliasChoices("WEBPACK_DEV_SERVER_PORT")
    )
    WEBPACK_LOADER: Any = Field(
        default=None
    )  # DERIVED: reproduce in a @model_validator (conditional/computed value)
    WSGI_APPLICATION: str = Field(default="odl_video.wsgi.application")
    YT_ACCESS_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_ACCESS_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_CLIENT_ID: str = Field(default="", validation_alias=AliasChoices("YT_CLIENT_ID"))
    YT_CLIENT_SECRET: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_CLIENT_SECRET")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_PROJECT_ID: str = Field(
        default="", validation_alias=AliasChoices("YT_PROJECT_ID")
    )
    YT_REFRESH_TOKEN: str | None = Field(
        default=None, validation_alias=AliasChoices("YT_REFRESH_TOKEN")
    )  # REDACTED: name looks secret-like — set via a source, not here
    YT_UPLOAD_LIMIT: int = Field(
        default=4, validation_alias=AliasChoices("YT_UPLOAD_LIMIT")
    )
    # <<< aqueduct:generated:fields

    # >>> aqueduct:generated:container_decoders
    @field_validator(
        "ALLOWED_HOSTS",
        "CELERY_ACCEPT_CONTENT",
        "INSTALLED_APPS",
        "MANDATORY_SETTINGS",
        "MIDDLEWARE",
        "POST_TRANSCODE_ACTIONS",
        "SOCIAL_AUTH_KEYCLOAK_EXTRA_DATA",
        "SOCIAL_AUTH_KEYCLOAK_SCOPE",
        "SOCIAL_AUTH_PIPELINE",
        mode="before",
    )
    @classmethod
    def _aqueduct_decode_list_fields(cls, value: object) -> object:
        """Parse a list from a JSON, Python-literal, or comma-separated env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            try:
                parsed = ast.literal_eval(value)
            except (ValueError, SyntaxError):
                parsed = None
        if isinstance(parsed, list):
            return parsed
        stripped = value.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            stripped = stripped[1:-1].strip()
        if not stripped:
            return []
        return [item.strip() for item in stripped.split(",")]

    @field_validator("REST_FRAMEWORK", mode="before")
    @classmethod
    def _aqueduct_decode_dict_fields(cls, value: object) -> object:
        """Parse a dict from a JSON or Python-literal env string."""
        if not isinstance(value, str):
            return value
        try:
            parsed = json.loads(value)
        except (ValueError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            return parsed
        return ast.literal_eval(value)

    # <<< aqueduct:generated:container_decoders

    # >>> aqueduct:preserved:validators
    # ------------------------------------------------------------------ #
    # Hand-written field overrides (a later declaration in the class body #
    # replaces the generated one above).                                  #
    # ------------------------------------------------------------------ #

    # MANDATORY_SETTINGS (odl_video/settings.py ~451-486): these have no
    # meaningful default upstream (falsy "" / None) and are only guarded by
    # ui.apps.UIConfig.ready() at Django-app-ready time. They are modelled as
    # required here so a missing value fails fast at settings instantiation.
    # MANDATORY_SETTINGS / ENFORCE_MANDATORY_SETTINGS themselves stay in the
    # generated region purely because ui.apps.UIConfig still reads them at
    # runtime; the check it performs is now redundant but harmless.
    AWS_ACCESS_KEY_ID: str = Field()
    AWS_ACCOUNT_ID: str = Field()
    AWS_REGION: str = Field()
    AWS_ROLE_NAME: str = Field()
    AWS_SECRET_ACCESS_KEY: str = Field()
    CLOUDFRONT_KEY_ID: str = Field()
    # odl_video/settings.py reads this with envs.get_key, which unescapes and
    # byte-encodes the value; the field_validator below replicates that.
    CLOUDFRONT_PRIVATE_KEY: bytes = Field()
    DROPBOX_KEY: str = Field()
    DROPBOX_REFRESH_TOKEN: str = Field()
    DROPBOX_SECRET: str = Field()
    GA_DIMENSION_CAMERA: str = Field()
    GA_KEYFILE_JSON: str = Field()
    GA_VIEW_ID: str = Field()
    LECTURE_CAPTURE_USER: str = Field()
    MAILGUN_KEY: str = Field()
    MAILGUN_URL: str = Field()
    ODL_VIDEO_BASE_URL: str = Field()
    REDIS_URL: str = Field()
    SECRET_KEY: str = Field()
    VIDEO_CDN_DISTRIBUTION_ID: str = Field()
    VIDEO_CLOUDFRONT_DIST: str = Field()
    VIDEO_S3_BUCKET: str = Field()
    VIDEO_S3_SUBTITLE_BUCKET: str = Field()
    VIDEO_S3_THUMBNAIL_BUCKET: str = Field()
    VIDEO_S3_TRANSCODE_BUCKET: str = Field()
    VIDEO_S3_WATCH_BUCKET: str = Field()
    YT_ACCESS_TOKEN: str = Field()
    YT_CLIENT_ID: str = Field()
    YT_CLIENT_SECRET: str = Field()
    YT_REFRESH_TOKEN: str = Field()
    # In odl_video/settings.py this was read with a hardcoded fallback secret
    # committed to git. Made required here (no default); the value must come
    # from the environment / Vault.
    KEYCLOAK_SVC_ADMIN_PASSWORD: str = Field()

    # Secret-shaped names are generated with `default=None` (REDACTED), but
    # odl_video/settings.py defaults these to "" — restore that so the model
    # stays value-for-value compatible with the legacy module.
    EMAIL_HOST_PASSWORD: str = Field(
        default="", validation_alias=AliasChoices("ODL_VIDEO_EMAIL_PASSWORD")
    )
    FIELD_ENCRYPTION_KEY: str = Field(default="")
    OPENEDX_API_CLIENT_SECRET: str = Field(default="")
    SENTRY_DSN: str = Field(default="")
    # Keep the env alias on the override: without it pydantic-settings falls
    # back to matching the field name (which happens to equal the env var here,
    # so it still worked), but stating it explicitly matches the generated
    # field and keeps KEYCLOAK_SERVER_URL / KEYCLOAK_REALM derivation reading
    # the real env value instead of the dev fallbacks.
    SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL: str = Field(
        default="",
        validation_alias=AliasChoices("SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL"),
    )
    SOCIAL_AUTH_KEYCLOAK_SECRET: str = Field(default="")

    # DATABASE_URL / ODL_VIDEO_DB_CONN_MAX_AGE / ODL_VIDEO_DB_DISABLE_SSL are
    # only ever read inline in odl_video/settings.py while building
    # DEFAULT_DATABASE_CONFIG, never assigned to a module global, so static
    # discovery cannot model them. Declared by hand so DATABASES stays
    # configurable through the source chain.
    DATABASE_URL: str | None = Field(default=None)
    ODL_VIDEO_DB_CONN_MAX_AGE: int = Field(default=0)
    ODL_VIDEO_DB_DISABLE_SSL: bool = Field(default=False)

    # Recomputed at import time instead of frozen to the generation machine.
    BASE_DIR: str = Field(default_factory=lambda: _DEFAULT_BASE_DIR)

    # ------------------------------------------------------------------ #
    # Sources                                                             #
    # ------------------------------------------------------------------ #

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        """Append the FEATURE_* env scan to the default source chain.

        The trailing ``_FeatureFlagEnvSource`` feeds dynamic ``FEATURE_*`` keys
        through the source chain so ``derivations.feature_flags`` can read them.
        List/dict env values (comma/Python-literal strings) are handled by the
        generator-emitted ``NoDecode`` + ``_aqueduct_decode_*_fields``
        validators in the ``aqueduct:generated:container_decoders`` region, so
        no custom env source is needed.
        """
        return (
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
            _FeatureFlagEnvSource(settings_cls),
        )

    # ------------------------------------------------------------------ #
    # Field validators                                                    #
    # ------------------------------------------------------------------ #

    @field_validator("CLOUDFRONT_PRIVATE_KEY", mode="before")
    @classmethod
    def _unescape_private_key(cls, value):
        """Replicate odl_video.envs.get_key: unescape `\\n` and byte-encode."""
        if isinstance(value, str):
            return value.encode().decode("unicode_escape").encode()
        return value

    # ------------------------------------------------------------------ #
    # Derivations, ported from odl_video/settings.py. Reusable pieces come #
    # from django_aqueduct.derivations.                                    #
    # ------------------------------------------------------------------ #

    @model_validator(mode="after")
    def _validate_upload_timing_windows(self) -> "AqueductSettings":
        """Port of odl_video/settings.py ~389-405."""
        if (
            self.CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS
            >= self.STUCK_UPLOADING_THRESHOLD_HOURS * 3600
        ):
            raise ImproperlyConfigured(
                "CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS must be below the "
                "janitor threshold (STUCK_UPLOADING_THRESHOLD_HOURS) or "
                "healthy uploads get reaped."
            )
        if (
            self.CLOUDSYNC_STREAM_S3_LOCK_TTL
            <= self.CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS
        ):
            raise ImproperlyConfigured(
                "CLOUDSYNC_STREAM_S3_LOCK_TTL must exceed "
                "CLOUDSYNC_UPLOAD_PROGRESS_REFRESH_SECONDS so the lock "
                "heartbeat can reacquire before the lease expires."
            )
        if self.CLOUDSYNC_STREAM_S3_LOCK_TTL >= self.CELERY_BROKER_VISIBILITY_TIMEOUT:
            raise ImproperlyConfigured(
                "CLOUDSYNC_STREAM_S3_LOCK_TTL must stay below "
                "CELERY_BROKER_VISIBILITY_TIMEOUT so a dead worker's lock "
                "expires before its task is redelivered."
            )
        return self

    @model_validator(mode="after")
    def _derive(self) -> "AqueductSettings":
        """Populate every DERIVED field, in legacy evaluation order."""
        base_dir = self.BASE_DIR

        # --- BASE_DIR-relative paths (settings.py ~55-64, ~197-211, ~260-262)
        self.STATIC_ROOT = os.path.join(base_dir, "staticfiles")
        self.STATICFILES_DIRS = (os.path.join(base_dir, "static"),)
        self.TEMPLATES = [
            {
                "BACKEND": "django.template.backends.django.DjangoTemplates",
                "DIRS": [base_dir + "/templates/"],
                "APP_DIRS": True,
                "OPTIONS": {
                    "context_processors": [
                        "django.template.context_processors.debug",
                        "django.template.context_processors.request",
                        "django.contrib.auth.context_processors.auth",
                        "django.contrib.messages.context_processors.messages",
                    ],
                },
            },
        ]
        self.WEBPACK_LOADER = {
            "DEFAULT": {
                "CACHE": not self.DEBUG,
                "BUNDLE_DIR_NAME": "bundles/",
                "STATS_FILE": os.path.join(base_dir, "webpack-stats.json"),
                "POLL_INTERVAL": 0.1,
                "TIMEOUT": None,
                "IGNORE": [r".+\.hot-update\.+", r".+\.js\.map"],
            }
        }

        # --- Databases (settings.py ~221-235), via derivations.database_config:
        # never applies sslmode to SQLite, and merges (rather than clobbers)
        # OPTIONS parsed from DATABASE_URL.
        database_url = self.DATABASE_URL or "sqlite:///{0}".format(
            os.path.join(base_dir, "db.sqlite3")
        )
        db_config = dv.database_config(
            database_url,
            conn_max_age=self.ODL_VIDEO_DB_CONN_MAX_AGE,
            ssl_require=not self.ODL_VIDEO_DB_DISABLE_SSL,
        )
        self.DEFAULT_DATABASE_CONFIG = db_config
        self.DATABASES = {"default": db_config}

        # --- Conditional app / middleware / auth branches
        # (settings.py ~89-128, ~614-618)
        installed = list(self.INSTALLED_APPS)
        middleware = list(self.MIDDLEWARE)
        if not self.DISABLE_WEBPACK_LOADER_STATS:
            installed.append("webpack_loader")
        if self.DEBUG:
            installed.append("nplusone.ext.django")
            middleware.append("nplusone.ext.django.NPlusOneMiddleware")
        if self.USE_KEYCLOAK:
            middleware.append("social_django.middleware.SocialAuthExceptionMiddleware")
            installed.append("social_django")
            self.AUTHENTICATION_BACKENDS = [
                "social_core.backends.keycloak.KeycloakOAuth2",
            ]
            self.LOGIN_URL = "/auth/login/keycloak/"
        else:
            self.AUTHENTICATION_BACKENDS = [
                "django.contrib.auth.backends.ModelBackend",
            ]
        if self.MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
            middleware += [
                "odl_video.middleware.QueryStringFeatureFlagMiddleware",
                "odl_video.middleware.CookieFeatureFlagMiddleware",
            ]
        self.INSTALLED_APPS = installed
        self.MIDDLEWARE = middleware

        # --- Keycloak URL derivation (settings.py ~141-159)
        token_url = self.SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL
        if "/realms/" in token_url:
            kc_server_default = token_url.split("/realms/")[0]
            kc_realm_default = token_url.split("/realms/")[1].split("/")[0]
        else:
            kc_server_default = "http://kc.odl.local:7080"
            kc_realm_default = "ovs-local"
        self.KEYCLOAK_SERVER_URL = self.KEYCLOAK_SERVER_URL or kc_server_default
        self.KEYCLOAK_REALM = self.KEYCLOAK_REALM or kc_realm_default
        self.SOCIAL_AUTH_KEYCLOAK_LOGOUT_URL = (
            self.SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL.replace(
                "/protocol/openid-connect/auth", "/protocol/openid-connect/logout"
            )
        )

        # --- ADMINS (settings.py ~293-297), via derivations.admins_from_csv
        self.ADMINS = (
            tuple(dv.admins_from_csv(f"Admins <{self.ADMIN_EMAIL}>"))
            if self.ADMIN_EMAIL
            else ()
        )

        # --- Static / CDN URLs (settings.py ~322-335)
        self.VIDEO_CLOUDFRONT_BASE_URL = self.VIDEO_CLOUDFRONT_BASE_URL or (
            "https://{}.cloudfront.net/".format(self.VIDEO_CLOUDFRONT_DIST)
        )
        if self.CLOUDFRONT_DIST:
            self.STATIC_URL = urljoin(
                "https://{dist}.cloudfront.net".format(dist=self.CLOUDFRONT_DIST),
                self.STATIC_URL,
            )
            self.AWS_S3_CUSTOM_DOMAIN = "{dist}.cloudfront.net".format(
                dist=self.CLOUDFRONT_DIST
            )
        else:
            # The legacy module leaves AWS_S3_CUSTOM_DOMAIN undefined in this
            # branch; the model always carries it (None) for a stable schema.
            self.AWS_S3_CUSTOM_DOMAIN = None

        # --- S3 transfer config (settings.py ~318-362)
        self.MB = self.KB * self.KB
        self.AWS_S3_UPLOAD_TRANSFER_CONFIG = dict(
            multipart_threshold=self.AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB * self.MB,
            multipart_chunksize=self.AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB * self.MB,
            max_concurrency=self.AWS_S3_UPLOAD_MAX_CONCURRENCY,
            num_download_attempts=self.AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS,
            max_io_queue=self.AWS_S3_UPLOAD_MAX_IO_QUEUE,
            io_chunksize=self.AWS_S3_UPLOAD_IO_CHUNKSIZE_KB * self.KB,
            use_threads=self.AWS_S3_UPLOAD_USE_THREADS,
        )

        # --- Redis / Celery / caches (settings.py ~499-581), via
        # derivations.first_url / derivations.redis_cache
        self.CELERY_BROKER_URL = dv.first_url(self.CELERY_BROKER_URL, self.REDIS_URL)
        self.CELERY_RESULT_BACKEND = self.REDIS_URL
        # Respect an explicitly-set CELERY_REDBEAT_REDIS_URL (e.g. a distinct
        # TLS "lowercase literal" URL) instead of silently discarding it; fall
        # back to the broker URL only when it is unset. Legacy assigned it
        # unconditionally from CELERY_BROKER_URL, so the unset case is
        # unchanged and parity holds.
        self.CELERY_REDBEAT_REDIS_URL = dv.first_url(
            self.CELERY_REDBEAT_REDIS_URL, self.CELERY_BROKER_URL
        )
        self.CELERY_REDIS_MAX_CONNECTIONS = self.REDIS_MAX_CONNECTIONS
        self.CELERY_BROKER_TRANSPORT_OPTIONS = {
            "visibility_timeout": self.CELERY_BROKER_VISIBILITY_TIMEOUT,
        }
        self.CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "local-in-memory-cache",
            },
            "redis": dv.redis_cache(
                self.CELERY_BROKER_URL,
                CLIENT_CLASS="django_redis.client.DefaultClient",
                CONNECTION_POOL_KWARGS={"max_connections": self.REDIS_MAX_CONNECTIONS},
            ),
        }

        # --- Feature flags (settings.py ~584-595), via
        # derivations.feature_flags: reads the model (which the
        # _FeatureFlagEnvSource and any Vault/SSM source feed), never
        # os.environ, so Vault-supplied flags are seen too.
        prefix = self.ODL_VIDEO_FEATURES_PREFIX
        self.FEATURES = dv.feature_flags(self, prefix=prefix)
        # Consume the raw FEATURE_* extras: the legacy module exposes flags
        # only under FEATURES, never as individual top-level settings.
        extras = self.__pydantic_extra__
        if extras:
            for key in [k for k in extras if k.startswith(prefix) and k.isupper()]:
                del extras[key]

        # --- Conditional beat entries (settings.py ~561-565, ~598-602).
        # The dev-only "update-statuses" task (every 10s!) must never run
        # outside dev environments.
        beat_schedule = dict(self.CELERY_BEAT_SCHEDULE)
        if self.ENVIRONMENT.lower() == "dev":
            beat_schedule["update-statuses"] = {
                "task": "cloudsync.tasks.update_video_statuses",
                "schedule": get_int("VIDEO_STATUS_UPDATE_FREQUENCY", 10),
            }
        if self.FEATURES.get("RETRANSCODE_ENABLED", False):
            beat_schedule["schedule_retranscodes"] = {
                "task": "cloudsync.tasks.schedule_retranscodes",
                "schedule": get_int("SCHEDULE_RETRANSCODE_FREQUENCY", 600),
            }
        self.CELERY_BEAT_SCHEDULE = beat_schedule

        return self

    # <<< aqueduct:preserved:validators


class DevAqueductSettings(AqueductSettings):
    """Local-dev variant: layers a Vault source on top of AqueductSettings.

    Follows the ``django_aqueduct.sources.dev`` (``VaultDevBase``) pattern:
    every Vault parameter comes from the ``VAULT_*`` environment —
    ``VAULT_ADDR`` (required to enable Vault), ``VAULT_PATH`` (required when
    enabled), ``VAULT_MOUNT``, ``VAULT_KV_VERSION``, ``VAULT_AUTH_METHOD``
    (token/oidc/kubernetes), ``VAULT_TOKEN``, ``VAULT_ROLE``. When
    ``VAULT_ADDR`` is unset this behaves exactly like ``AqueductSettings``
    (no Vault, no crash), and a partially-configured Vault environment raises
    an actionable ``VaultConfigError`` instead of a bare ``KeyError``.
    """

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls,
        init_settings,
        env_settings,
        dotenv_settings,
        file_secret_settings,
    ):
        """Prepend the env-configured Vault source when it is available."""
        base = super().settings_customise_sources(
            settings_cls,
            init_settings,
            env_settings,
            dotenv_settings,
            file_secret_settings,
        )
        vault = vault_source_from_env(settings_cls)
        return (vault, *base) if vault is not None else base
