"""
Django settings for odl_video project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""
import ast
import logging
import os
import platform
from urllib.parse import urljoin

import dj_database_url
import yaml

VERSION = "0.0.0"

CONFIG_PATHS = [
    os.environ.get('ODL_VIDEO_CONFIG', ''),
    os.path.join(os.getcwd(), 'odl_video.yml'),
    os.path.join(os.path.expanduser('~'), 'odl_video.yml'),
    '/etc/odl_video.yml',

]


def load_fallback():
    """Load optional yaml config"""
    fallback_config = {}
    config_file_path = None
    for config_path in CONFIG_PATHS:
        if os.path.isfile(config_path):
            config_file_path = config_path
            break
    if config_file_path is not None:
        with open(config_file_path) as config_file:
            fallback_config = yaml.safe_load(config_file)
    return fallback_config


FALLBACK_CONFIG = load_fallback()


def get_var(name, default):
    """Return the settings in a precedence way with default"""
    try:
        value = os.environ.get(name, FALLBACK_CONFIG.get(name, default))
        return ast.literal_eval(value)
    except (SyntaxError, ValueError):
        return value


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

SECRETS_DIR = get_var('SECRETS_DIR', '/run/secrets/')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY_FILE = os.path.join(SECRETS_DIR, "django-secret-key")
if os.path.isfile(SECRET_KEY_FILE):
    with open(SECRET_KEY_FILE, 'rb') as keyfile:
        SECRET_KEY = keyfile.read()
else:
    SECRET_KEY = get_var(
        'DJANGO_SECRET_KEY',
        'ls8t)o32h@bqp1s8e0&6+mepk#t4@^68yx43kjm_#tvdv=m&ke',
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_var('DEBUG', False)

ALLOWED_HOSTS = ['*']


WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [
            r'.+\.hot-update\.+',
            r'.+\.js\.map'
        ]
    }
}

# Request files from the webpack dev server
USE_WEBPACK_DEV_SERVER = get_var('ODL_VIDEO_SERVICE_USE_WEBPACK_DEV_SERVER', False)
WEBPACK_DEV_SERVER_HOST = get_var('WEBPACK_DEV_SERVER_HOST', '')
WEBPACK_DEV_SERVER_PORT = get_var('WEBPACK_DEV_SERVER_PORT', '8082')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'server_status',
    'raven.contrib.django.raven_compat',
    'ui.apps.UIConfig',
    'cloudsync.apps.CloudSyncConfig',
    'dj_elastictranscoder',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

DISABLE_WEBPACK_LOADER_STATS = get_var("DISABLE_WEBPACK_LOADER_STATS", False)
if not DISABLE_WEBPACK_LOADER_STATS:
    INSTALLED_APPS += ('webpack_loader',)

MIDDLEWARE_CLASSES = [
    'raven.contrib.django.raven_compat.middleware.SentryResponseErrorIdMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if get_var('USE_SHIBBOLETH', False):
    # TOUCHSTONE
    MIDDLEWARE_CLASSES.append('shibboleth.middleware.ShibbolethRemoteUserMiddleware')
    SHIBBOLETH_ATTRIBUTE_MAP = {
        "EPPN": (True, "username"),
        "MAIL": (True, "email"),
        # full name is in the "DISPLAY_NAME" header,
        # but no way to parse that into first_name and last_name...
    }
    AUTHENTICATION_BACKENDS = [
        'shibboleth.backends.ShibbolethRemoteUserBackend',
    ]
    LOGIN_URL = "/Shibboleth.sso/Login"
else:
    LOGIN_URL = "/login/"

ROOT_URLCONF = 'odl_video.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'odl_video.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# Uses DATABASE_URL to configure with sqlite default:
# For URL structure:
# https://github.com/kennethreitz/dj-database-url
DEFAULT_DATABASE_CONFIG = dj_database_url.parse(
    get_var(
        'DATABASE_URL',
        'sqlite:///{0}'.format(os.path.join(BASE_DIR, 'db.sqlite3'))
    )
)
DEFAULT_DATABASE_CONFIG['CONN_MAX_AGE'] = int(get_var('ODL_VIDEO_DB_CONN_MAX_AGE', 0))

if get_var('ODL_VIDEO_DB_DISABLE_SSL', False):
    DEFAULT_DATABASE_CONFIG['OPTIONS'] = {}
else:
    DEFAULT_DATABASE_CONFIG['OPTIONS'] = {'sslmode': 'require'}

DATABASES = {
    'default': DEFAULT_DATABASE_CONFIG
}


# Celery
# http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
USE_CELERY = True
CELERY_BROKER_URL = get_var("REDIS_URL", None)
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

CELERY_TASK_ALWAYS_EAGER = get_var("CELERY_TASK_ALWAYS_EAGER", False)
CELERY_TASK_EAGER_PROPAGATES = get_var("CELERY_TASK_EAGER_PROPAGATES", True)

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'


# django cache back-ends
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'local-in-memory-cache',
    },
    'redis': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": CELERY_BROKER_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
    },
}


# features flags
def get_all_config_keys():
    """Returns all the configuration keys from both environment and configuration files"""
    return list(set(os.environ.keys()).union(set(FALLBACK_CONFIG.keys())))


ODL_VIDEO_FEATURES_PREFIX = get_var('ODL_VIDEO_FEATURES_PREFIX', 'FEATURE_')
FEATURES = {
    key[len(ODL_VIDEO_FEATURES_PREFIX):]: get_var(key, None) for key
    in get_all_config_keys() if key.startswith(ODL_VIDEO_FEATURES_PREFIX)
}

MIDDLEWARE_FEATURE_FLAG_QS_PREFIX = get_var("MIDDLEWARE_FEATURE_FLAG_QS_PREFIX", None)
MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME = get_var(
    'MIDDLEWARE_FEATURE_FLAG_COOKIE_NAME', 'ODL_VIDEO_FEATURE_FLAGS')
MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS = get_var(
    'MIDDLEWARE_FEATURE_FLAG_COOKIE_MAX_AGE_SECONDS', 60 * 60)

if MIDDLEWARE_FEATURE_FLAG_QS_PREFIX:
    MIDDLEWARE_CLASSES = MIDDLEWARE_CLASSES + (
        'odl_video.middleware.QueryStringFeatureFlagMiddleware',
        'odl_video.middleware.CookieFeatureFlagMiddleware',
    )


# enable the nplusone profiler only in debug mode
if DEBUG:
    INSTALLED_APPS += (
        'nplusone.ext.django',
    )
    MIDDLEWARE_CLASSES += (
        'nplusone.ext.django.NPlusOneMiddleware',
    )


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
CLOUDFRONT_DIST = get_var('STATIC_CLOUDFRONT_DIST', None)
if CLOUDFRONT_DIST:
    STATIC_URL = urljoin('https://{dist}.cloudfront.net'.format(dist=CLOUDFRONT_DIST), STATIC_URL)
    AWS_S3_CUSTOM_DOMAIN = '{dist}.cloudfront.net'.format(dist=CLOUDFRONT_DIST)

STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# OTHER
LOGIN_REDIRECT_URL = "/"

# Important to define this so DEBUG works properly
INTERNAL_IPS = (get_var('HOST_IP', '127.0.0.1'), )

# Configure e-mail settings
EMAIL_BACKEND = get_var('ODL_VIDEO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = get_var('ODL_VIDEO_EMAIL_HOST', 'localhost')
EMAIL_PORT = get_var('ODL_VIDEO_EMAIL_PORT', 25)
EMAIL_HOST_USER = get_var('ODL_VIDEO_EMAIL_USER', '')
EMAIL_HOST_PASSWORD = get_var('ODL_VIDEO_EMAIL_PASSWORD', '')
EMAIL_USE_TLS = get_var('ODL_VIDEO_EMAIL_TLS', False)
EMAIL_SUPPORT = get_var('ODL_VIDEO_SUPPORT_EMAIL', 'support@example.com')
DEFAULT_FROM_EMAIL = get_var('ODL_VIDEO_FROM_EMAIL', 'webmaster@localhost')

MAILGUN_URL = get_var('MAILGUN_URL', 'https://api.mailgun.net/v3/micromasters.mit.edu')
MAILGUN_KEY = get_var('MAILGUN_KEY', None)
MAILGUN_BATCH_CHUNK_SIZE = get_var('MAILGUN_BATCH_CHUNK_SIZE', 1000)
MAILGUN_RECIPIENT_OVERRIDE = get_var('MAILGUN_RECIPIENT_OVERRIDE', None)
MAILGUN_FROM_EMAIL = get_var('MAILGUN_FROM_EMAIL', 'no-reply@example.com')
MAILGUN_BCC_TO_EMAIL = get_var('MAILGUN_BCC_TO_EMAIL', 'no-reply@example.com')


# e-mail configurable admins
ADMIN_EMAIL = get_var('ODL_VIDEO_ADMIN_EMAIL', '')
if ADMIN_EMAIL != '':
    ADMINS = (('Admins', ADMIN_EMAIL),)
else:
    ADMINS = ()

# Logging configuration
LOG_LEVEL = get_var('ODL_VIDEO_LOG_LEVEL', 'INFO')
DJANGO_LOG_LEVEL = get_var('DJANGO_LOG_LEVEL', 'INFO')

# For logging to a remote syslog host
LOG_HOST = get_var('ODL_VIDEO_LOG_HOST', 'localhost')
LOG_HOST_PORT = get_var('ODL_VIDEO_LOG_HOST_PORT', 514)

HOSTNAME = platform.node().split('.')[0]
DEFAULT_LOG_STANZA = {
    'handlers': ['console', 'syslog'],
    'level': LOG_LEVEL,
}

# nplusone profiler logger configuration
NPLUSONE_LOGGER = logging.getLogger('nplusone')
NPLUSONE_LOG_LEVEL = logging.ERROR

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'formatters': {
        'verbose': {
            'format': (
                '[%(asctime)s] %(levelname)s %(process)d [%(name)s] '
                '%(filename)s:%(lineno)d - '
                '[{hostname}] - %(message)s'
            ).format(hostname=HOSTNAME),
            'datefmt': '%Y-%m-%d %H:%M:%S'
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'syslog': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.SysLogHandler',
            'facility': 'local7',
            'formatter': 'verbose',
            'address': (LOG_HOST, LOG_HOST_PORT)
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'sentry': {
            'level': 'ERROR',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'root': DEFAULT_LOG_STANZA,
        'odl_video': DEFAULT_LOG_STANZA,
        'django': {
            'propagate': True,
            'level': DJANGO_LOG_LEVEL,
            'handlers': ['console', 'syslog'],
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        'urllib3': {
            'level': 'INFO',
        },
        'raven': {
            'level': 'DEBUG',
            'handlers': []
        },
        'nplusone': {
            'handlers': ['console'],
            'level': 'ERROR',
        }
    },
}

# AWS S3 upload settings
# the defaults values come from the default configuration in boto3.s3.transfer.TransferConfig
# apart from the first 2
KB = 1024
MB = KB * KB

# AWS
AWS_ACCESS_KEY_ID = get_var('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = get_var('AWS_SECRET_ACCESS_KEY', '')
AWS_REGION = get_var('AWS_REGION', '')
AWS_S3_DOMAIN = get_var('AWS_S3_DOMAIN', 's3.amazonaws.com')

AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB = get_var('AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB', 32)
AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB = get_var('AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB', 32)
AWS_S3_UPLOAD_MAX_CONCURRENCY = get_var('AWS_S3_UPLOAD_MAX_CONCURRENCY', 10)
AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS = get_var('AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS', 5)
AWS_S3_UPLOAD_MAX_IO_QUEUE = get_var('AWS_S3_UPLOAD_MAX_IO_QUEUE', 100)
AWS_S3_UPLOAD_IO_CHUNKSIZE_KB = get_var('AWS_S3_UPLOAD_IO_CHUNKSIZE_KB', 256)
AWS_S3_UPLOAD_USE_THREADS = get_var('AWS_S3_UPLOAD_USE_THREADS', True)

AWS_S3_UPLOAD_TRANSFER_CONFIG = dict(
    multipart_threshold=AWS_S3_UPLOAD_MULTIPART_THRESHOLD_MB * MB,
    multipart_chunksize=AWS_S3_UPLOAD_MULTIPART_CHUNKSIZE_MB * MB,
    max_concurrency=AWS_S3_UPLOAD_MAX_CONCURRENCY,
    num_download_attempts=AWS_S3_UPLOAD_NUM_DOWNLOAD_ATTEMPTS,
    max_io_queue=AWS_S3_UPLOAD_MAX_IO_QUEUE,
    io_chunksize=AWS_S3_UPLOAD_IO_CHUNKSIZE_KB * KB,
    use_threads=AWS_S3_UPLOAD_USE_THREADS
)

# AWS ElasticTranscoder
ET_PIPELINE_ID = get_var('ET_PIPELINE_ID', '')
# not using get_var for the following because the values in the strings would be interpreted as single instructions
ET_PRESET_IDS = os.environ.get(
    'ET_PRESET_IDS',
    '1351620000001-200010,1351620000001-200020,1351620000001-200050'
).split(',')

VIDEO_CLOUDFRONT_DIST = get_var('VIDEO_CLOUDFRONT_DIST', '')
VIDEO_S3_BUCKET = get_var('VIDEO_S3_BUCKET', 'odl-video-service')
VIDEO_S3_TRANSCODE_BUCKET = get_var('VIDEO_S3_TRANSCODE_BUCKET', '{}-transcoded'.format(VIDEO_S3_BUCKET))
VIDEO_S3_THUMBNAIL_BUCKET = get_var('VIDEO_S3_THUMBNAIL_BUCKET', '{}-thumbnails'.format(VIDEO_S3_BUCKET))

# server-status
STATUS_TOKEN = get_var("STATUS_TOKEN", "")
HEALTH_CHECK = ['CELERY', 'REDIS', 'POSTGRES']

ADWORDS_CONVERSION_ID = get_var("ADWORDS_CONVERSION_ID", "")
GA_TRACKING_ID = get_var("GA_TRACKING_ID", "")
REACT_GA_DEBUG = get_var("REACT_GA_DEBUG", False)
