# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-15 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0007_collections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Uploading", "Uploading"),
                    ("Upload failed", "Upload failed"),
                    ("Transcoding", "Transcoding"),
                    (
                        "Transcode failed internal error",
                        "Transcode failed internal error",
                    ),
                    ("Transcode failed video error", "Transcode failed video error"),
                    ("Complete", "Complete"),
                    ("Error", "Error"),
                ],
                default="Created",
                max_length=50,
            ),
        ),
    ]
