# Generated by Django 1.10.5 on 2017-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0010_video_default_sort"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-created_at"]},
        ),
    ]
