# Generated by Django 1.10.5 on 2017-09-12 19:55

from datetime import datetime

import pytz
from django.db import migrations, models


def populate_collection_created_at(apps, schema_editor):
    """Populate values"""
    Collection = apps.get_model("ui", "Collection")

    for collection in Collection.objects.iterator():
        collection.created_at = datetime.now(tz=pytz.utc)
        collection.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0011_collection_created_at"),
    ]

    operations = [
        migrations.RunPython(populate_collection_created_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="collection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
