# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_video_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ui.Video')),
                ('id', models.CharField(max_length=11, null=True)),
                ('status', models.CharField(default='uploading', max_length=24)),
            ],
        ),
    ]
