# Generated by Django 1.11.10 on 2018-03-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0016_collection_stream_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
