# Generated by Django 1.11.10 on 2018-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0020_collection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="source_url",
            field=models.URLField(max_length=2000),
        ),
    ]
