# Generated by Django 2.1.7 on 2019-06-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_video_custom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allow_share_openedx',
            field=models.BooleanField(default=False),
        ),
    ]
