# Generated by Django 2.1.7 on 2019-11-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_add_collection_edx_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='schedule_retranscode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='schedule_retranscode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Uploading', 'Uploading'), ('Upload failed', 'Upload failed'), ('Transcoding', 'Transcoding'), ('Transcode failed internal error', 'Transcode failed internal error'), ('Transcode failed video error', 'Transcode failed video error'), ('Retranscoding', 'Retranscoding'), ('Complete', 'Complete'), ('Error', 'Error')], default='Created', max_length=50),
        ),
    ]
