# Generated by Django 2.2.13 on 2021-11-12 18:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0031_replace_global_default_endpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edxendpoint",
            name="client_id",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="edxendpoint",
            name="secret_key",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
