# Generated by Django 2.2.13 on 2022-11-30 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0032_encryption_fields_sizing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edxendpoint",
            old_name="hls_api_path",
            new_name="edx_video_api_path",
        ),
    ]
