# Generated by Django 4.2.19 on 2025-03-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0033_rename_hls_api_path_to_edx_video_api_path"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collectionedxendpoint",
            unique_together={("collection", "edx_endpoint")},
        ),
    ]
