# Generated by Django 4.2.20 on 2025-04-09 12:16

from django.db import migrations, models, connection
import django.db.models.deletion


def migrate_encodejob_data(apps, schema_editor):
    """Copy data from the old table to the new model."""
    EncodeJob = apps.get_model("ui", "EncodeJob")
    db_alias = schema_editor.connection.alias

    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT id, object_id, state, message, created_at, last_modified, content_type_id
            FROM dj_elastictranscoder_encodejob
        """)
        rows = cursor.fetchall()

    new_jobs = [
        EncodeJob(
            id=row[0],
            object_id=row[1],
            state=row[2],
            message=row[3],
            created_at=row[4],
            last_modified=row[5],
            content_type_id=row[6],
        )
        for row in rows
    ]

    EncodeJob.objects.using(db_alias).bulk_create(new_jobs)


def drop_old_encodejob_table(apps, schema_editor):
    """Drop the old dj_elastictranscoder_encodejob table."""
    with connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS dj_elastictranscoder_encodejob")


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ui", "0034_add_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncodeJob",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "state",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Submitted"),
                            (1, "Progressing"),
                            (2, "Error"),
                            (3, "Warning"),
                            (4, "Complete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_encodejob_data),
        migrations.RunPython(drop_old_encodejob_table),
    ]
