# Generated by Django 4.2.20 on 2025-04-21 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ui", "0034_add_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncodeJob",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "state",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Submitted"),
                            (1, "Progressing"),
                            (2, "Error"),
                            (3, "Warning"),
                            (4, "Complete"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("message", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
