# Generated by Django 4.2.20 on 2025-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0035_encodejob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encodejob",
            name="message",
            field=models.JSONField(),
        ),
    ]
