# Generated by Django 4.2.21 on 2025-05-23 01:10

from ast import literal_eval
from django.db import migrations, models, connection


def migrate_video_duration(apps, schema_editor):
    """
    Migrate video duration from the old encode job if data exists.
    """

    if (
        "dj_elastictranscoder_encodejob"
        in schema_editor.connection.introspection.table_names()
    ):
        Video = apps.get_model("ui", "Video")
        db_alias = schema_editor.connection.alias

        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT e1.object_id, e1.message
                FROM dj_elastictranscoder_encodejob e1
                INNER JOIN (
                    SELECT object_id, MAX(created_at) as max_created_at
                    FROM dj_elastictranscoder_encodejob
                    WHERE state = 4
                    GROUP BY object_id
                ) e2 ON e1.object_id = e2.object_id AND e1.created_at = e2.max_created_at
                WHERE e1.state = 4
                """
            )
            rows = cursor.fetchall()

        for row in rows:
            video_id, message = row
            try:
                # Attempt to parse the message as a literal
                message = literal_eval(message)
            except (ValueError, SyntaxError, TypeError):
                # If parsing fails, skip this row
                continue

            if duration := (
                message
                and isinstance(message, dict)
                and message.get("Output", {}).get("Duration")
            ):
                Video.objects.using(db_alias).filter(id=video_id).update(
                    duration=duration
                )
    EncodeJob = apps.get_model("ui", "EncodeJob")
    encode_jobs = EncodeJob.objects.using(db_alias).filter(state=4)
    for job in encode_jobs:
        video_id = job.object_id
        if not video_id:
            continue
        # Fetch the video object
        video = Video.objects.using(db_alias).get(id=video_id)
        if video and (not video.duration):
            if output_groups := job.message.get("outputGroupDetails", []):
                # Get the first output group
                output_group = output_groups[0]
                if outputs := output_group.get("outputDetails", []):
                    # Get the first output
                    output = outputs[0]
                    duration_in_ms = output.get("durationInMs", 0)
                    # Convert milliseconds to seconds
                    duration = duration_in_ms / 1000.0
                    video.duration = duration
                    video.save(update_fields=["duration"])


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0035_encodejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.RunPython(migrate_video_duration, migrations.RunPython.noop),
    ]
