# Generated by Django 4.2.21 on 2025-05-23 01:10

from ast import literal_eval
from django.db import migrations, models, connection


def migrate_video_duration(apps, schema_editor):
    """
    Migrate video duration from the old encode job.
    """
    Video = apps.get_model("ui", "Video")
    db_alias = schema_editor.connection.alias

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT e1.object_id, e1.message 
            FROM dj_elastictranscoder_encodejob e1
            INNER JOIN (
                SELECT object_id, MAX(created_at) as max_created_at
                FROM dj_elastictranscoder_encodejob
                WHERE state = 4
                GROUP BY object_id
            ) e2 ON e1.object_id = e2.object_id AND e1.created_at = e2.max_created_at
            WHERE e1.state = 4
        """
        )
        rows = cursor.fetchall()

    for row in rows:
        video_id, message = row
        if not (message := literal_eval(message)):
            continue

        duration = isinstance(message, dict) and message.get("Output", {}).get(
            "Duration"
        )

        if duration:
            Video.objects.using(db_alias).filter(id=video_id).update(duration=duration)


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0035_encodejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.RunPython(migrate_video_duration, migrations.RunPython.noop),
    ]
