# Generated by Django on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0036_video_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
