# Generated by Django 4.2.23 on 2025-08-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0036_video_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoiraList',
            new_name='KeycloakGroup',
        ),
    ]
