# Generated by Django 4.2.28 on 2026-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0036_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cta_link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
