# Generated by Django 4.2.28 on 2026-03-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ui", "0038_video_cta_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="include_in_learn",
            field=models.BooleanField(default=False),
        ),
    ]
