# Generated by Django 4.2.30 on 2026-04-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0040_rename_moiralist_keycloakgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='for_shorts',
            field=models.BooleanField(default=False),
        ),
    ]
