# Generated by Django 4.2.30 on 2026-05-12 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0041_collection_for_shorts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videothumbnail',
            options={'ordering': ['-created_at']},
        ),
    ]
