# Uncomment after we upload docker images
# FROM mitodl/odl_video_service_watch_travis
FROM python:3.6.8-stretch
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

RUN mkdir /src

WORKDIR /src

COPY package.json yarn.lock ./webpack_if_prod.sh /src/
COPY scripts /src/scripts
RUN node /src/scripts/install_yarn.js

RUN yarn install --frozen-lockfile

COPY . /src

USER root

RUN chown -R node:node /src

USER node
