# Uncomment after we upload docker images
# FROM mitodl/odl_video_service_watch_travis
FROM node:6.2
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

RUN mkdir /src

WORKDIR /src

RUN adduser --disabled-password --gecos "" mitodl

COPY package.json yarn.lock ./webpack_if_prod.sh /src/
COPY scripts /src/scripts
RUN node /src/scripts/install_yarn.js

RUN yarn install --pure-lockfile

COPY . /src

USER root

RUN chown -R mitodl:mitodl /src

USER mitodl
