# Commented out since this image doesn't exist yet
# FROM mitodl/odl_video_service_web_travis_next
FROM python:3.6.8-stretch

WORKDIR /tmp

USER root

COPY requirements.txt /tmp/requirements.txt
COPY test_requirements.txt /tmp/test_requirements.txt
RUN pip install -r requirements.txt -r test_requirements.txt

# odl_video_service_web_travis comes with a copy of the source which may not match the current copy, so we need to copy it again
RUN rm -rf /src
RUN mkdir /src

WORKDIR /src

COPY . /src

RUN adduser --disabled-password --gecos "" mitodl
RUN chown -R mitodl:mitodl /src

USER mitodl
