# Generated by Django 1.11.10 on 2018-05-02 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0003_default_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationemail",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notificationemail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
